

import { Language, NavSection } from './types';
import { LayoutDashboard, Calculator, Percent, Wallet, ShieldAlert, MessageSquareText, ArrowRightLeft, Umbrella, CreditCard } from 'lucide-react';

export const APP_NAME = "ArithMitra";

export const LANG_DISPLAY_NAMES: Record<Language, string> = {
  [Language.EN]: "English",
  [Language.HI]: "हिंदी (Hindi)",
  [Language.MR]: "मराठी (Marathi)",
  [Language.GU]: "ગુજરાતી (Gujarati)",
  [Language.TA]: "தமிழ் (Tamil)",
  [Language.TE]: "తెలుగు (Telugu)",
  [Language.KN]: "ಕನ್ನಡ (Kannada)",
  [Language.BN]: "বাংলা (Bengali)",
};

export const NAV_ITEMS: { id: NavSection; icon: any; label: Record<Language, string>; description?: Record<Language, string> }[] = [
  { 
    id: 'dashboard', 
    icon: LayoutDashboard, 
    label: { 
      en: 'Dashboard', 
      hi: 'डैशबोर्ड', 
      mr: 'डॅशबोर्ड',
      gu: 'ડેશબોર્ડ',
      ta: 'முகப்பு',
      te: 'డ్యాష్‌బోర్డ్',
      kn: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
      bn: 'ড্যাশবোর্ড'
    },
    description: {
      en: 'Overview of your financial health.',
      hi: 'आपके वित्तीय स्वास्थ्य का अवलोकन।',
      mr: 'तुमच्या आर्थिक आरोग्याचा आढावा.',
      gu: 'તમારા નાણાકીય સ્વાસ્થ્યની ઝાંખી.',
      ta: 'உங்கள் நிதி ஆரோக்கியத்தின் கண்ணோட்டம்.',
      te: 'మీ ఆర్థిక ఆరోగ్యం యొక్క అవలోకనం.',
      kn: 'ನಿಮ್ಮ ಹಣಕಾಸಿನ ಆರೋಗ್ಯದ ಅವಲೋಕನ.',
      bn: 'আপনার আর্থিক স্বাস্থ্যের ওভারভিউ।'
    }
  },
  { 
    id: 'credit', 
    icon: CreditCard, 
    label: { 
      en: 'Credit Score', 
      hi: 'क्रेडिट स्कोर', 
      mr: 'क्रेडिट स्कोर',
      gu: 'ક્રેડિટ સ્કોર',
      ta: 'கிரெடிட் ஸ்கோர்',
      te: 'క్రెడిట్ స్కోర్',
      kn: 'ಕ್ರೆಡಿಟ್ ಸ್ಕೋರ್',
      bn: 'ক্রেডিট স্কোর'
    },
    description: {
      en: 'Check score & card eligibility.',
      hi: 'स्कोर और कार्ड पात्रता जांचें।',
      mr: 'स्कोर आणि कार्ड पात्रता तपासा.',
      gu: 'સ્કોર અને કાર્ડ પાત્રતા તપાસો.',
      ta: 'ஸ்கோர் மற்றும் அட்டை தகுதியை சரிபார்க்கவும்.',
      te: 'స్కోరు మరియు కార్డ్ అర్హతను తనిఖీ చేయండి.',
      kn: 'ಸ್ಕೋರ್ ಮತ್ತು ಕಾರ್ಡ್ ಅರ್ಹತೆಯನ್ನು ಪರಿಶೀಲಿಸಿ.',
      bn: 'স্কোর এবং কার্ড যোগ্যতা পরীক্ষা করুন।'
    }
  },
  { 
    id: 'transfer', 
    icon: ArrowRightLeft, 
    label: { 
      en: 'Money Transfer', 
      hi: 'मनी ट्रांसफर', 
      mr: 'पैसे पाठवा',
      gu: 'મની ટ્રાન્સફર',
      ta: 'பண பரிமாற்றம்',
      te: 'డబ్బు బదిలీ',
      kn: 'ಹಣ ವರ್ಗಾವಣೆ',
      bn: 'টাকা স্থানান্তর'
    },
    description: {
      en: 'Send money securely.',
      hi: 'सुरक्षित रूप से पैसे भेजें।',
      mr: 'सुरक्षितपणे पैसे पाठवा.',
      gu: 'સુરક્ષિત રીતે પૈસા મોકલો.',
      ta: 'பாதுகாப்பாக பணம் அனுப்பவும்.',
      te: 'సురక్షితంగా డబ్బు పంపండి.',
      kn: 'ಸುರಕ್ಷಿತವಾಗಿ ಹಣ ಕಳುಹಿಸಿ.',
      bn: 'নিরাপদে টাকা পাঠান।'
    }
  },
  { 
    id: 'insurance', 
    icon: Umbrella, 
    label: { 
      en: 'Insurance', 
      hi: 'बीमा', 
      mr: 'विमा',
      gu: 'વીમો',
      ta: 'காப்பீடு',
      te: 'బీమా',
      kn: 'ವಿಮೆ',
      bn: 'বীমা'
    },
    description: {
      en: 'Compare plans & calculate premiums.',
      hi: 'योजनाओं की तुलना करें और प्रीमियम की गणना करें।',
      mr: 'योजनांची तुलना करा आणि प्रीमियम मोजा.',
      gu: 'યોજનાઓની તુલના કરો અને પ્રીમિયમની ગણતરી કરો.',
      ta: 'திட்டங்களை ஒப்பிட்டு பிரீமியங்களைக் கணக்கிடுங்கள்.',
      te: 'ప్లాన్‌లను సరిపోల్చండి & ప్రీమియంలను లెక్కించండి.',
      kn: 'ಯೋಜನೆಗಳನ್ನು ಹೋಲಿಕೆ ಮಾಡಿ ಮತ್ತು ಪ್ರೀಮಿಯಂ ಲೆಕ್ಕ ಹಾಕಿ.',
      bn: 'পরিকল্পনা তুলনা করুন এবং প্রিমিয়াম গণনা করুন।'
    }
  },
  { 
    id: 'emi', 
    icon: Calculator, 
    label: { 
      en: 'EMI Calculator', 
      hi: 'ईएमआई कैलकुलेटर', 
      mr: 'ईएमआई कॅल्क्युलेटर',
      gu: 'EMI કેલ્ક્યુલેટર',
      ta: 'EMI கால்குலேட்டர்',
      te: 'EMI காலిక్యులేటర్',
      kn: 'EMI ಕ್ಯಾಲ್ಕುಲೇಟರ್',
      bn: 'EMI ক্যালকুলেটর'
    },
    description: {
      en: 'Plan your loans with precision.',
      hi: 'सटीकता के साथ अपने ऋण की योजना बनाएं।',
      mr: 'अचूकतेने आपल्या कर्जाचे नियोजन करा.',
      gu: 'ચોકસાઈ સાથે તમારી લોનનું આયોજન કરો.',
      ta: 'உங்கள் கடன்களை துல்லியமாக திட்டமிடுங்கள்.',
      te: 'మీ రుణాలను ఖచ్చితత్వంతో ప్లాన్ చేయండి.',
      kn: 'ನಿಮ್ಮ ಸಾಲಗಳನ್ನು ನಿಖರವಾಗಿ ಯೋಜಿಸಿ.',
      bn: 'নির্ভুলতার সাথে আপনার ঋণের পরিকল্পনা করুন।'
    }
  },
  { 
    id: 'loan', 
    icon: Percent, 
    label: { 
      en: 'Loan Predictor', 
      hi: 'ऋण पात्रता', 
      mr: 'कर्ज पात्रता',
      gu: 'લોન પાત્રતા',
      ta: 'கடன் தகுதி',
      te: 'రుణ అర్హత',
      kn: 'ಸಾಲ ಅರ್ಹತೆ',
      bn: 'ঋণের যোগ্যতা'
    },
    description: {
      en: 'AI-based eligibility check.',
      hi: 'एआई-आधारित पात्रता जाँच।',
      mr: 'AI-आधारित पात्रता तपासणी.',
      gu: 'AI-આધારિત પાત્રતા તપાસ.',
      ta: 'AI-அடிப்படையிலான தகுதி சரிபார்ப்பு.',
      te: 'AI-ఆధారిత అర్హత తనిఖీ.',
      kn: 'AI-ಆಧಾರಿತ ಅರ್ಹತಾ ಪರಿಶೀಲನೆ.',
      bn: 'AI-ভিত্তিক যোগ্যতা পরীক্ষা।'
    }
  },
  { 
    id: 'expense', 
    icon: Wallet, 
    label: { 
      en: 'Expense Tracker', 
      hi: 'व्यय ट्रैकर', 
      mr: 'खर्च ट्रॅकर',
      gu: 'ખર્ચ ટ્રેકર',
      ta: 'செலவு டிராக்கர்',
      te: 'ఖర్చు ట్రాకర్',
      kn: 'ವೆಚ್ಚ ಟ್ರ್ಯಾಕರ್',
      bn: 'খরಚ ট্র্যাকার'
    },
    description: {
      en: 'Monitor daily spending habits.',
      hi: 'दैनिक खर्च की आदतों की निगरानी करें।',
      mr: 'दैनंदिन खर्चाच्या सवयींवर लक्ष ठेवा.',
      gu: 'દૈનિક ખર્ચની આદતોનું નિરીક્ષણ કરો.',
      ta: 'தினசரி செலவு பழக்கங்களைக் கண்காணிக்கவும்.',
      te: 'రోజువారీ ఖర్చు అలవాట్లను పర్యవేక్షించండి.',
      kn: 'ದೈನಂದಿನ ಖರ್ಚು ಅಭ್ಯಾಸಗಳನ್ನು ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡಿ.',
      bn: 'দৈনিক খরচের অভ্যাস মনিটর করুন।'
    }
  },
  { 
    id: 'fraud', 
    icon: ShieldAlert, 
    label: { 
      en: 'Fraud Detector', 
      hi: 'धोखाधड़ी डिटेक्टर', 
      mr: 'फसवणूक शोधक',
      gu: 'છેતરપિંડી ડિટેક્ટર',
      ta: 'மோசடி கண்டுபிடிப்பாளர்',
      te: 'మోసం డిటెక్టర్',
      kn: 'ವಂಚನೆ ಪತ್ತೆದರ',
      bn: 'প্রতারণা সনাক্তকারী'
    },
    description: {
      en: 'Scan messages for scams.',
      hi: 'घोटालों के लिए संदेशों को स्कैन करें।',
      mr: 'स्कॅमसाठी संदेश स्कॅन करा.',
      gu: 'કૌભાંડો માટે સંદેશાઓ સ્કેન કરો.',
      ta: 'மோசடிகளுக்கு செய்திகளை ஸ்கேன் செய்யவும்.',
      te: 'స్కామ్‌ల కోసం సందేశాలను స్కాన్ చేయండి.',
      kn: 'ಹಗರಣಗಳಿಗಾಗಿ ಸಂದೇಶಗಳನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ.',
      bn: 'স্ক্যামের জন্য বার্তা স্ক্যান করুন।'
    }
  },
  { 
    id: 'chat', 
    icon: MessageSquareText, 
    label: { 
      en: 'FinBot AI', 
      hi: 'फिनबॉट एआई', 
      mr: 'फिनबॉट एआई',
      gu: 'ફિનબોટ AI',
      ta: 'ஃபின்பாட் AI',
      te: 'ఫిన్‌బాట్ AI',
      kn: 'ಫಿನ್‌ಬಾಟ್ AI',
      bn: 'ফিনবট AI'
    },
    description: {
      en: 'Your personal financial assistant.',
      hi: 'आपका व्यक्तिगत वित्तीय सहायक।',
      mr: 'तुमचा वैयक्तिक आर्थिक सहाय्यक.',
      gu: 'તમારા વ્યક્તિગત નાણાકીય સહાયક.',
      ta: 'உங்கள் தனிப்பட்ட நிதி உதவியாளர்.',
      te: 'మీ వ్యక్తిగత ఆర్థిక సహాయకుడు.',
      kn: 'ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಹಣಕಾಸು ಸಹಾಯಕ.',
      bn: 'আপনার ব্যক্তিগত আর্থিক সহকারী।'
    }
  },
];

export const TRANSLATIONS = {
  [Language.EN]: {
    welcome: "Welcome back",
    loginSubtitle: "Sign in to access your financial tools",
    login: "Login",
    signup: "Sign Up",
    email: "Email Address",
    password: "Password",
    name: "Full Name",
    logout: "Logout",
    totalExpenses: "Total Expenses",
    monthlyBudget: "Monthly Budget",
    remaining: "Remaining",
    recentActivity: "Recent Activity",
    calculate: "Calculate",
    amount: "Amount",
    interestRate: "Interest Rate (%)",
    tenure: "Tenure (Years)",
    monthlyEMI: "Monthly EMI",
    totalInterest: "Total Interest",
    totalPayment: "Total Payment",
    analyze: "Analyze",
    fraudPlaceholder: "Paste the suspicious SMS or Email text here...",
    fraudTitle: "Fraud Message Detector",
    safe: "Likely Safe",
    suspicious: "Suspicious",
    dangerous: "Dangerous",
    expenseTitle: "Expense Tracker",
    addExpense: "Add Expense",
    category: "Category",
    date: "Date",
    loanTitle: "AI Loan Eligibility",
    income: "Monthly Income",
    creditScore: "Credit Score",
    existingEmi: "Existing EMIs",
    predict: "Predict Eligibility",
    chatPlaceholder: "Ask me anything about finance...",
    analyzing: "Analyzing...",
    processing: "Processing...",
    heroTitle: "Your Intelligent Financial Companion",
    heroSubtitle: "Master your money with AI-driven insights, fraud protection, and smart calculators.",
    getStarted: "Get Started Free",
    noAccount: "Don't have an account? Sign Up",
    hasAccount: "Already have an account? Login",
    loginError: "Invalid email or password.",
    signupError: "User already exists. Please login.",
    userNotFound: "User not found. Please Sign Up first.",
    features: "Features",
    transferTitle: "Money Transfer",
    recipient: "Recipient Name",
    accountNo: "Account Number / UPI ID",
    sendMoney: "Send Money",
    successMsg: "Transaction Successful!",
    history: "Transaction History",
    walletBalance: "Wallet Balance",
    insuranceTitle: "Insurance Advisor",
    lifeInsurance: "Life Insurance",
    healthInsurance: "Health Insurance",
    vehicleInsurance: "Vehicle Insurance",
    age: "Age",
    coverage: "Coverage Amount",
    premium: "Estimated Premium",
    getQuote: "Get Quote",
    recommended: "Recommended Plans",
    googleLogin: "Continue with Google",
    signupSuccess: "Account created! Please log in.",
    valName: "Name is required",
    valEmail: "Please enter a valid email address",
    valPass: "Password must be at least 6 characters",
    paymentMethod: "Payment Method",
    payWith: "Pay with",
    processingPayment: "Processing Payment...",
    enterPin: "Enter UPI PIN",
    pinPlaceholder: "Enter 4-digit PIN",
    invalidPin: "Invalid PIN",
    securePayment: "Secure Payment",
    paying: "Paying",
    currentScore: "Current Score",
    scoreHistory: "Score History",
    factors: "Key Factors",
    checkScore: "Refresh Score",
    paymentHistory: "Payment History",
    utilization: "Credit Utilization",
    impact: "Impact",
    excellent: "Excellent",
    good: "Good",
    fair: "Fair",
    poor: "Poor",
    enterDetails: "Enter Details",
    panNumber: "PAN Number",
    dob: "Date of Birth",
    mobileNumber: "Mobile Number",
    checkNow: "Check Now",
    cardEligibility: "Card Eligibility",
    checkEligibility: "Check Eligibility",
    recommendedCards: "Recommended Cards",
    applyNow: "Apply Now",
    annualFee: "Annual Fee",
    joiningFee: "Joining Fee",
    salaried: "Salaried",
    selfEmployed: "Self Employed",
    student: "Student",
    employmentType: "Employment Type",
    invalidPan: "Invalid PAN Number format (e.g., ABCDE1234F)",
    invalidMobile: "Invalid Mobile Number (10 digits)",
  },
  [Language.HI]: {
    welcome: "वापसी पर स्वागत है",
    loginSubtitle: "अपने वित्तीय साधनों तक पहुँचने के लिए साइन इन करें",
    login: "लॉग इन करें",
    signup: "साइन अप करें",
    email: "ईमेल पता",
    password: "पासवर्ड",
    name: "पूरा नाम",
    logout: "लॉग आउट",
    totalExpenses: "कुल व्यय",
    monthlyBudget: "मासिक बजट",
    remaining: "शेष",
    recentActivity: "हाल की गतिविधि",
    calculate: "गणना करें",
    amount: "राशि",
    interestRate: "ब्याज दर (%)",
    tenure: "अवधि (वर्ष)",
    monthlyEMI: "मासिक ईएमआई",
    totalInterest: "कुल ब्याज",
    totalPayment: "कुल भुगतान",
    analyze: "विश्लेषण करें",
    fraudPlaceholder: "संदिग्ध एसएमएस या ईमेल टेक्स्ट यहाँ पेस्ट करें...",
    fraudTitle: "धोखाधड़ी संदेश डिटेक्टर",
    safe: "संभवतः सुरक्षित",
    suspicious: "संदिग्ध",
    dangerous: "खतरनाक",
    expenseTitle: "व्यय ट्रैकर",
    addExpense: "व्यय जोड़ें",
    category: "श्रेणी",
    date: "तारीख",
    loanTitle: "एआई ऋण पात्रता",
    income: "मासिक आय",
    creditScore: "क्रेडिट स्कोर",
    existingEmi: "मौजूदा ईएमआई",
    predict: "पात्रता की भविष्यवाणी करें",
    chatPlaceholder: "वित्त के बारे में मुझसे कुछ भी पूछें...",
    analyzing: "विश्लेषण कर रहा है...",
    processing: "प्रक्रिया जारी है...",
    heroTitle: "आपका बुद्धिमान वित्तीय साथी",
    heroSubtitle: "एआई-संचालित अंतर्दृष्टि, धोखाधड़ी सुरक्षा और स्मार्ट कैलकुलेटर के साथ अपने पैसे में महारत हासिल करें।",
    getStarted: "मुफ्त में शुरू करें",
    noAccount: "खाता नहीं है? साइन अप करें",
    hasAccount: "पहले से खाता है? लॉग इन करें",
    loginError: "अमान्य ईमेल या पासवर्ड।",
    signupError: "उपयोगकर्ता पहले से मौजूद है। कृपया लॉग इन करें।",
    userNotFound: "उपयोगकर्ता नहीं मिला। कृपया पहले साइन अप करें।",
    features: "विशेषताएँ",
    transferTitle: "मनी ट्रांसफर",
    recipient: "प्राप्तकर्ता का नाम",
    accountNo: "खाता संख्या / UPI ID",
    sendMoney: "पैसे भेजें",
    successMsg: "लेनदेन सफल!",
    history: "लेनदेन इतिहास",
    walletBalance: "वॉलेट बैलेंस",
    insuranceTitle: "बीमा सलाहकार",
    lifeInsurance: "जीवन बीमा",
    healthInsurance: "स्वास्थ्य बीमा",
    vehicleInsurance: "वाहन बीमा",
    age: "आयु",
    coverage: "कवरेज राशि",
    premium: "अनुमानित प्रीमियम",
    getQuote: "उद्धरण प्राप्त करें",
    recommended: "अनुशंसित योजनाएं",
    googleLogin: "Google के साथ जारी रखें",
    signupSuccess: "खाता बनाया गया! कृपया लॉग इन करें।",
    valName: "नाम आवश्यक है",
    valEmail: "कृपया एक मान्य ईमेल पता दर्ज करें",
    valPass: "पासवर्ड कम से कम 6 अक्षरों का होना चाहिए",
    paymentMethod: "भुगतान का तरीका",
    payWith: "भुगतान करें",
    processingPayment: "भुगतान संसाधित हो रहा है...",
    enterPin: "UPI पिन दर्ज करें",
    pinPlaceholder: "4-अंकीय पिन दर्ज करें",
    invalidPin: "अमान्य पिन",
    securePayment: "सुरक्षित भुगतान",
    paying: "भुगतान कर रहा है",
    currentScore: "वर्तमान स्कोर",
    scoreHistory: "स्कोर इतिहास",
    factors: "प्रमुख कारक",
    checkScore: "स्कोर रिफ्रेश करें",
    paymentHistory: "भुगतान इतिहास",
    utilization: "क्रेडिट उपयोग",
    impact: "प्रभाव",
    excellent: "उत्कृष्ट",
    good: "अच्छा",
    fair: "ठीक",
    poor: "खराब",
    enterDetails: "विवरण दर्ज करें",
    panNumber: "पैन नंबर",
    dob: "जन्म तिथि",
    mobileNumber: "मोबाइल नंबर",
    checkNow: "अभी जांचें",
    cardEligibility: "कार्ड पात्रता",
    checkEligibility: "पात्रता जाँचें",
    recommendedCards: "अनुशंसित कार्ड",
    applyNow: "अभी आवेदन करें",
    annualFee: "वार्षिक शुल्क",
    joiningFee: "शामिल होने का शुल्क",
    salaried: "वेतनभोगी",
    selfEmployed: "स्वरोजगार",
    student: "छात्र",
    employmentType: "रोजगार का प्रकार",
    invalidPan: "अमान्य पैन नंबर प्रारूप",
    invalidMobile: "अमान्य मोबाइल नंबर",
  },
  [Language.MR]: {
    welcome: "परत स्वागत आहे",
    loginSubtitle: "तुमच्या आर्थिक साधनांमध्ये प्रवेश करण्यासाठी साइन इन करें",
    login: "लॉग इन",
    signup: "साइन अप",
    email: "ईमेल पत्ता",
    password: "पासवर्ड",
    name: "पूर्ण नाव",
    logout: "लॉग आउट",
    totalExpenses: "एकूण खर्च",
    monthlyBudget: "मासिक बजेट",
    remaining: "शिल्लक",
    recentActivity: "अलीकडील क्रियाकलाप",
    calculate: "गणना करा",
    amount: "रक्कम",
    interestRate: "व्याज दर (%)",
    tenure: "मुदत (वर्षे)",
    monthlyEMI: "मासिक EMI",
    totalInterest: "एकूण व्याज",
    totalPayment: "एकूण देयक",
    analyze: "विश्लेषण करा",
    fraudPlaceholder: "संशयास्पद एसएमएस किंवा ईमेल मजकूर येथे पेस्ट करा...",
    fraudTitle: "फसवणूक संदेश शोधक",
    safe: "संभाव्यतः सुरक्षित",
    suspicious: "संशयास्पद",
    dangerous: "धोकादायक",
    expenseTitle: "खर्च ट्रॅकर",
    addExpense: "खर्च जोडा",
    category: "श्रेणी",
    date: "तारीख",
    loanTitle: "AI कर्ज पात्रता",
    income: "मासिक उत्पन्न",
    creditScore: "क्रेडिट स्कोअर",
    existingEmi: "विद्यमान ईएमआय",
    predict: "पात्रता अंदाजित करा",
    chatPlaceholder: "मला वित्तबद्दल काहीही विचारा...",
    analyzing: "विश्लेषण करत आहे...",
    processing: "प्रक्रिया सुरू आहे...",
    heroTitle: "तुमचा बुद्धिमान आर्थिक सोबती",
    heroSubtitle: "AI-आधारित अंतर्दृष्टी, फसवणूक संरक्षण आणि स्मार्ट कॅल्क्युलेटरसह आपल्या पैशावर प्रभुत्व मिळवा.",
    getStarted: "मोफत सुरू करा",
    noAccount: "खाते नाही? साइन अप करा",
    hasAccount: "आधीच खाते आहे? लॉग इन करा",
    loginError: "अवैध ईमेल किंवा पासवर्ड.",
    signupError: "वापरकर्ता आधीच अस्तित्वात आहे. कृपया लॉग इन करा.",
    userNotFound: "वापरकर्ता सापडला नाही. कृपया प्रथम साइन अप करा.",
    features: "वैशिष्ट्ये",
    transferTitle: "पैसे पाठवा",
    recipient: "प्राप्तकर्त्याचे नाव",
    accountNo: "खाते क्रमांक / UPI आयडी",
    sendMoney: "पैसे पाठवा",
    successMsg: "व्यवहार यशस्वी!",
    history: "व्यवहार इतिहास",
    walletBalance: "वॉलेट शिल्लक",
    insuranceTitle: "विमा सल्लागार",
    lifeInsurance: "जीवन विमा",
    healthInsurance: "आरोग्य विमा",
    vehicleInsurance: "वाहन विमा",
    age: "वय",
    coverage: "कव्हरेज रक्कम",
    premium: "अंदाजित प्रीमियम",
    getQuote: "कोट मिळवा",
    recommended: "शिफारस केलेल्या योजना",
    googleLogin: "Google सह चालू ठेवा",
    signupSuccess: "खाते तयार झाले! कृपया लॉग इन करा.",
    valName: "नाव आवश्यक आहे",
    valEmail: "कृपया वैध ईमेल पत्ता प्रविष्ट करा",
    valPass: "पासवर्ड किमान 6 अक्षरांचा असावा",
    paymentMethod: "पेमेंट पद्धत",
    payWith: "द्वारे पैसे द्या",
    processingPayment: "पेमेंट प्रक्रिया सुरू आहे...",
    enterPin: "UPI पिन प्रविष्ट करा",
    pinPlaceholder: "4-अंकी पिन प्रविष्ट करा",
    invalidPin: "अवैध पिन",
    securePayment: "सुरक्षित पेमेंट",
    paying: "पैसे देत आहे",
    currentScore: "सध्याचा स्कोर",
    scoreHistory: "स्कोर इतिहास",
    factors: "मुख्य घटक",
    checkScore: "स्कोर रिफ्रेश करा",
    paymentHistory: "पेमेंट इतिहास",
    utilization: "क्रेडिट वापर",
    impact: "प्रभाव",
    excellent: "उत्कृष्ट",
    good: "चांगला",
    fair: "ठीक",
    poor: "खराब",
    enterDetails: "तपशील प्रविष्ट करा",
    panNumber: "पॅन नंबर",
    dob: "जन्म तारीख",
    mobileNumber: "मोबाईल नंबर",
    checkNow: "आता तपासा",
    cardEligibility: "कार्ड पात्रता",
    checkEligibility: "पात्रता तपासा",
    recommendedCards: "शिफारस केलेले कार्ड",
    applyNow: "आताच अर्ज करा",
    annualFee: "वार्षिक फी",
    joiningFee: "सामील होण्याची फी",
    salaried: "पगारदार",
    selfEmployed: "स्वयंरोजगार",
    student: "विद्यार्थी",
    employmentType: "रोजगार प्रकार",
    invalidPan: "अवैध पॅन नंबर फॉरमॅट",
    invalidMobile: "अवैध मोबाईल नंबर",
  },
  [Language.GU]: {
    welcome: "સ્વાગત છે",
    loginSubtitle: "તમારા નાણાકીય સાધનોને ઍક્સેસ કરવા માટે સાઇન ઇન કરો",
    login: "લોગ ઇન",
    signup: "સાઇન અપ",
    email: "ઇમેઇલ સરનામું",
    password: "પાસવર્ડ",
    name: "પૂરું નામ",
    logout: "લોગ આઉટ",
    totalExpenses: "કુલ ખર્ચ",
    monthlyBudget: "માસિક બજેટ",
    remaining: "બાકી",
    recentActivity: "તાજેતરની પ્રવૃત્તિ",
    calculate: "ગણતરી કરો",
    amount: "રકમ",
    interestRate: "વ્યાજ દર (%)",
    tenure: "મુદત (વર્ષ)",
    monthlyEMI: "માસિક EMI",
    totalInterest: "કુલ વ્યાજ",
    totalPayment: "કુલ ચુકવણી",
    analyze: "વિશ્લેષણ કરો",
    fraudPlaceholder: "શંકાસ્પદ SMS અથવા ઇમેઇલ ટેક્સ્ટ અહીં પેસ્ટ કરો...",
    fraudTitle: "છેતરપિંડી સંદેશ ડિટેક્ટર",
    safe: "સંભવિત સુરક્ષિત",
    suspicious: "શંકાસ્પદ",
    dangerous: "ખતરનાક",
    expenseTitle: "ખર્ચ ટ્રેકર",
    addExpense: "ખર્ચ ઉમેરો",
    category: "શ્રેણી",
    date: "તારીખ",
    loanTitle: "AI લોન પાત્રતા",
    income: "માસિક આવક",
    creditScore: "ક્રેડિટ સ્કોર",
    existingEmi: "વર્તમાન EMI",
    predict: "પાત્રતાની આગાહી કરો",
    chatPlaceholder: "નાણાકીય બાબતો વિશે મને કંઈ પણ પૂછો...",
    analyzing: "વિશ્લેષણ કરી રહ્યું છે...",
    processing: "પ્રક્રિયા ચાલુ છે...",
    heroTitle: "તમારા બુદ્ધિશાળી નાણાકીય સાથી",
    heroSubtitle: "AI-આધારિત આંતરદૃષ્ટિ, છેતરપિંડી સુરક્ષા અને સ્માર્ટ કેલ્ક્યુલેટર સાથે તમારા પૈસા પર પ્રભુત્વ મેળવો.",
    getStarted: "મફત શરૂ કરો",
    noAccount: "ખાતું નથી? સાઇન અપ કરો",
    hasAccount: "પહેલેથી જ ખાતું છે? લોગ ઇન કરો",
    loginError: "અમાન્ય ઇમેઇલ અથવા પાસવર્ડ.",
    signupError: "વપરાશકર્તા પહેલેથી જ અસ્તિત્વમાં છે. કૃપા કરીને લોગ ઇન કરો.",
    userNotFound: "વપરાશકર્તા મળ્યા નથી. કૃપા કરીને પહેલા સાઇન અપ કરો.",
    features: "વિશેષતાઓ",
    transferTitle: "મની ટ્રાન્સફર",
    recipient: "પ્રાપ્તકર્તાનું નામ",
    accountNo: "ખાતા નંબર / UPI ID",
    sendMoney: "પૈસા મોકલો",
    successMsg: "વ્યવહાર સફળ!",
    history: "વ્યવહાર ઇતિહાસ",
    walletBalance: "વોલેટ બેલેન્સ",
    insuranceTitle: "વીમા સલાહકાર",
    lifeInsurance: "જીવન વીમો",
    healthInsurance: "સ્વાસ્થ્ય વીમો",
    vehicleInsurance: "વાહન વીમો",
    age: "ઉંમર",
    coverage: "કવરેજ રકમ",
    premium: "અંદાજિત પ્રીમિયમ",
    getQuote: "ક્વોટ મેળવો",
    recommended: "ભલામણ કરેલ યોજનાઓ",
    googleLogin: "Google સાથે ચાલુ રાખો",
    signupSuccess: "ખાતું બની ગયું! કૃપા કરીને લોગ ઇન કરો.",
    valName: "નામ જરૂરી છે",
    valEmail: "કૃપા કરીને માન્ય ઇમેઇલ સરનામું દાખલ કરો",
    valPass: "પાસવર્ડ ઓછામાં ઓછા 6 અક્ષરોનો હોવો જોઈએ",
    paymentMethod: "ચુકવણી પદ્ધતિ",
    payWith: "દ્વારા ચૂકવો",
    processingPayment: "ચુકવણી પ્રક્રિયા ચાલુ છે...",
    enterPin: "UPI પિન દાખલ કરો",
    pinPlaceholder: "4-અંકનો પિન દાખલ કરો",
    invalidPin: "અમાન્ય પિન",
    securePayment: "સુરક્ષિત ચુકવણી",
    paying: "ચૂકવણી કરી રહ્યા છીએ",
    currentScore: "વર્તમાન સ્કોર",
    scoreHistory: "સ્કોર ઇતિહાસ",
    factors: "મુખ્ય પરિબળો",
    checkScore: "સ્કોર અપડેટ કરો",
    paymentHistory: "ચુકવણી ઇતિહાસ",
    utilization: "ક્રેડિટ ઉપયોગ",
    impact: "અસર",
    excellent: "ઉત્તમ",
    good: "સારું",
    fair: "સામાન્ય",
    poor: "ખરાબ",
    enterDetails: "વિગતો દાખલ કરો",
    panNumber: "પાન નંબર",
    dob: "જન્મ તારીખ",
    mobileNumber: "મોબાઇલ નંબર",
    checkNow: "હવે તપાસો",
    cardEligibility: "કાર્ડ પાત્રતા",
    checkEligibility: "પાત્રતા તપાસો",
    recommendedCards: "ભલામણ કરેલ કાર્ડ્સ",
    applyNow: "હમણાં અરજી કરો",
    annualFee: "વાર્ષિક ફી",
    joiningFee: "જોડાવાની ફી",
    salaried: "પગારદાર",
    selfEmployed: "સ્વરોજગાર",
    student: "વિદ્યાર્થી",
    employmentType: "રોજગાર પ્રકાર",
    invalidPan: "અમાન્ય PAN ફોર્મેટ",
    invalidMobile: "અમાન્ય મોબાઇલ નંબર",
  },
  [Language.TA]: {
    welcome: "மீண்டும் வருக",
    loginSubtitle: "உங்கள் நிதிக் கருவிகளை அணுக உள்நுழையவும்",
    login: "உள்நுழைய",
    signup: "பதிவு செய்க",
    email: "மின்னஞ்சல் முகவரி",
    password: "கடவுச்சொல்",
    name: "முழு பெயர்",
    logout: "வெளியேறு",
    totalExpenses: "மொத்த செலவுகள்",
    monthlyBudget: "மாதாந்திர பட்ஜெட்",
    remaining: "மீதமுள்ள",
    recentActivity: "சமீபத்திய செயல்பாடு",
    calculate: "கணக்கிடு",
    amount: "தொகை",
    interestRate: "வட்டி விகிதம் (%)",
    tenure: "கால அளவு (ஆண்டுகள்)",
    monthlyEMI: "மாதாந்திர EMI",
    totalInterest: "மொத்த வட்டி",
    totalPayment: "மொத்த கட்டணம்",
    analyze: "பகுப்பாய்வு",
    fraudPlaceholder: "சந்தேகத்திற்குரிய SMS அல்லது மின்னஞ்சலை இங்கே ஒட்டவும்...",
    fraudTitle: "மோசடி செய்தி கண்டுபிடிப்பாளர்",
    safe: "பாதுகாப்பானது",
    suspicious: "சந்தேகத்திற்குரியது",
    dangerous: "ஆபத்தானது",
    expenseTitle: "செலவு டிராக்கர்",
    addExpense: "செலவைச் சேர்",
    category: "வகை",
    date: "தேதி",
    loanTitle: "AI கடன் தகுதி",
    income: "மாத வருமானம்",
    creditScore: "கிரெடிட் ஸ்கோர்",
    existingEmi: "தற்போதுள்ள EMI",
    predict: "தகுதியை கணி",
    chatPlaceholder: "நிதி பற்றி எதையும் கேளுங்கள்...",
    analyzing: "பகுப்பாய்வு செய்கிறது...",
    processing: "செயலாக்குகிறது...",
    heroTitle: "உங்கள் அறிவார்ந்த நிதித் தோழன்",
    heroSubtitle: "AI மூலம் உங்கள் பணத்தை நிர்வகிக்கவும், மோசடிகளிலிருந்து பாதுகாக்கவும்.",
    getStarted: "இலவசமாகத் தொடங்கவும்",
    noAccount: "கணக்கு இல்லையா? பதிவு செய்க",
    hasAccount: "ஏற்கனவே கணக்கு உள்ளதா? உள்நுழைய",
    loginError: "தவறான மின்னஞ்சல் அல்லது கடவுச்சொல்.",
    signupError: "பயனர் ஏற்கனவே உள்ளார். உள்நுழையவும்.",
    userNotFound: "பயனர் காணப்படவில்லை. பதிவு செய்யவும்.",
    features: "அம்சங்கள்",
    transferTitle: "பண பரிமாற்றம்",
    recipient: "பெறுநர் பெயர்",
    accountNo: "கணக்கு எண் / UPI ID",
    sendMoney: "பணம் அனுப்பு",
    successMsg: "பரிவர்த்தனை வெற்றிகரமானது!",
    history: "பரிவர்த்தனை வரலாறு",
    walletBalance: "வாலட் இருப்பு",
    insuranceTitle: "காப்பீட்டு ஆலோசகர்",
    lifeInsurance: "ஆயுள் காப்பீடு",
    healthInsurance: "மருத்துவ காப்பீடு",
    vehicleInsurance: "வாகன காப்பீடு",
    age: "வயது",
    coverage: "காப்பீட்டுத் தொகை",
    premium: "மதிப்பிடப்பட்ட பிரீமியம்",
    getQuote: "மதிப்பீடு பெறு",
    recommended: "பரிந்துரைக்கப்பட்ட திட்டங்கள்",
    googleLogin: "Google உடன் தொடரவும்",
    signupSuccess: "கணக்கு உருவாக்கப்பட்டது! உள்நுழையவும்.",
    valName: "பெயர் தேவை",
    valEmail: "சரியான மின்னஞ்சல் முகவரியை உள்ளிடவும்",
    valPass: "கடவுச்சொல் குறைந்தது 6 எழுத்துகள் இருக்க வேண்டும்",
    paymentMethod: "கட்டண முறை",
    payWith: "இதன் மூலம் செலுத்தவும்",
    processingPayment: "கட்டணம் செயலாக்கப்படுகிறது...",
    enterPin: "UPI பின்னை உள்ளிடவும்",
    pinPlaceholder: "4 இலக்க பின்னை உள்ளிடவும்",
    invalidPin: "தவறான பின்",
    securePayment: "பாதுகாப்பான கட்டணம்",
    paying: "செலுத்துகிறது",
    currentScore: "தற்போதைய ஸ்கோர்",
    scoreHistory: "ஸ்கோர் வரலாறு",
    factors: "முக்கிய காரணிகள்",
    checkScore: "ஸ்கோரை புதுப்பிக்கவும்",
    paymentHistory: "கட்டண வரலாறு",
    utilization: "கடன் பயன்பாடு",
    impact: "தாக்கம்",
    excellent: "சிறப்பானது",
    good: "நல்லது",
    fair: "நியாயமானது",
    poor: "மோசமானது",
    enterDetails: "விவரங்களை உள்ளிடவும்",
    panNumber: "பான் எண்",
    dob: "பிறந்த தேதி",
    mobileNumber: "அலைபேசி எண்",
    checkNow: "இப்போது சரிபார்க்கவும்",
    cardEligibility: "அட்டை தகுதி",
    checkEligibility: "தகுதியை சரிபார்க்கவும்",
    recommendedCards: "பரிந்துரைக்கப்பட்ட அட்டைகள்",
    applyNow: "இப்போது விண்ணப்பிக்கவும்",
    annualFee: "ஆண்டு கட்டணம்",
    joiningFee: "சேரும் கட்டணம்",
    salaried: "சம்பளம் பெறுபவர்",
    selfEmployed: "சுய தொழில்",
    student: "மாணவர்",
    employmentType: "வேலை வகை",
    invalidPan: "தவறான பான் வடிவமைப்பு",
    invalidMobile: "தவறான அலைபேசி எண்",
  },
  [Language.TE]: {
    welcome: "తిరిగి స్వాగతం",
    loginSubtitle: "మీ ఆర్థిక సాధనాలను యాక్సెస్ చేయడానికి సైన్ ఇన్ చేయండి",
    login: "లాగిన్",
    signup: "సైన్ అప్",
    email: "ఇమెయిల్ చిరునామా",
    password: "పాస్వర్డ్",
    name: "పూర్తి పేరు",
    logout: "లాగ్ అవుట్",
    totalExpenses: "మొత్తం ఖర్చులు",
    monthlyBudget: "నెలవారీ బడ్జెట్",
    remaining: "మిగిలినది",
    recentActivity: "ఇటీవలి కార్యాచరణ",
    calculate: "లెక్కించు",
    amount: "మొత్తం",
    interestRate: "వడ్డీ రేటు (%)",
    tenure: "కాలపరిమితి (సంవత్సరాలు)",
    monthlyEMI: "నెలవారీ EMI",
    totalInterest: "మొత్తం వడ్డీ",
    totalPayment: "మొత్తం చెల్లింపు",
    analyze: "విశ్లేించు",
    fraudPlaceholder: "అనుమానాస్పద SMS లేదా ఇమెయిల్‌ను ఇక్కడ పేస్ట్ చేయండి...",
    fraudTitle: "మోసం డిటెక్టర్",
    safe: "సురక్షితం",
    suspicious: "అనుమానాస్పదం",
    dangerous: "ప్రమాదకరం",
    expenseTitle: "ఖర్చు ట్రాకర్",
    addExpense: "ఖర్చు జోడించు",
    category: "వర్గం",
    date: "తేదీ",
    loanTitle: "AI రుణ అర్హత",
    income: "నెలవారీ ఆదాయం",
    creditScore: "క్రెడిట్ స్కోర్",
    existingEmi: "ప్రస్తుత EMIలు",
    predict: "అర్హతను అంచనా వేయండి",
    chatPlaceholder: "ఆర్థిక విషయాలపై నన్ను ఏమైనా అడగండి...",
    analyzing: "విశ్లేషిస్తోంది...",
    processing: "ప్రాసెస్ చేస్తోంది...",
    heroTitle: "మీ తెలివైన ఆర్థిక సహచరుడు",
    heroSubtitle: "AI, మోసాల రక్షణ మరియు స్మార్ట్ కాలిక్యులేటర్లతో మీ డబ్బును నిర్వహించండి.",
    getStarted: "ఉచితంగా ప్రారంభించండి",
    noAccount: "ఖాతా లేదా? సైన్ అప్",
    hasAccount: "ఇప్పటికే ఖాతా ఉందా? లాగిన్",
    loginError: "చెల్లని ఇమెయిల్ లేదా పాస్‌వర్డ్.",
    signupError: "వినియోగదారు ఇప్పటికే ఉన్నారు. దయచేసి లాగిన్ చేయండి.",
    userNotFound: "వినియోగదారు కనుగొనబడలేదు. దయచేసి సైన్ అప్ చేయండి.",
    features: "లక్షణాలు",
    transferTitle: "డబ్బు బదిలీ",
    recipient: "స్వీకర్త పేరు",
    accountNo: "ఖాతా సంఖ్య / UPI ID",
    sendMoney: "డబ్బు పంపండి",
    successMsg: "లావాదేవీ విజయవంతమైంది!",
    history: "లావాదేవీ చరిత్ర",
    walletBalance: "వాలెట్ బ్యాలెన్స్",
    insuranceTitle: "బీమా సలహాదారు",
    lifeInsurance: "జీవిత బీమా",
    healthInsurance: "ఆరోగ్య బీమా",
    vehicleInsurance: "వాహన బీమా",
    age: "వయస్సు",
    coverage: "కవరేజ్ మొత్తం",
    premium: "అంచనా వేసిన ప్రీమియం",
    getQuote: "కోట్ పొందండి",
    recommended: "సిఫార్సు చేసిన ప్లాన్లు",
    googleLogin: "Googleతో కొనసాగండి",
    signupSuccess: "ఖాతా సృష్టించబడింది! దయచేసి లాగిన్ చేయండి.",
    valName: "పేరు అవసరం",
    valEmail: "దయచేసి సరైన ఇమెయిల్ చిరునామాను నమోదు చేయండి",
    valPass: "పాస్‌వర్డ్ తప్పనిసరిగా కనీసం 6 అక్షరాలు ఉండాలి",
    paymentMethod: "చెల్లింపు పద్ధతి",
    payWith: "ద్వారా చెల్లించండి",
    processingPayment: "చెల్లింపును ప్రాసెస్ చేస్తోంది...",
    enterPin: "UPI పిన్‌ని నమోదు చేయండి",
    pinPlaceholder: "4-అంకెల పిన్‌ని నమోదు చేయండి",
    invalidPin: "చెల్లని పిన్",
    securePayment: "సురక్షిత చెల్లింపు",
    paying: "చెల్లిస్తున్నారు",
    currentScore: "ప్రస్తుత స్కోరు",
    scoreHistory: "స్కోరు చరిత్ర",
    factors: "ప్రధాన అంశాలు",
    checkScore: "స్కోరు రీఫ్రెష్ చేయండి",
    paymentHistory: "చెల్లింపు చరిత్ర",
    utilization: "క్రెడిట్ వినియోగం",
    impact: "ప్రభావం",
    excellent: "అద్భుతమైన",
    good: "మంచి",
    fair: "సాధారణ",
    poor: "బలహీనమైన",
    enterDetails: "వివరాలను నమోదు చేయండి",
    panNumber: "పాన్ నంబర్",
    dob: "పుట్టిన తేది",
    mobileNumber: "మొబైల్ నంబర్",
    checkNow: "ఇప్పుడే తనిఖీ చేయండి",
    cardEligibility: "కార్డ్ అర్హత",
    checkEligibility: "అర్హతను తనిఖీ చేయండి",
    recommendedCards: "సిఫార్సు చేయబడిన కార్డులు",
    applyNow: "ఇప్పుడే దరఖాస్తు చేయండి",
    annualFee: "వార్షిక రుసుము",
    joiningFee: "చేరడానికి రుసుము",
    salaried: "వేతన జీవి",
    selfEmployed: "స్వయం ఉపాధి",
    student: "విద్యార్థి",
    employmentType: "ఉద్యోగ రకం",
    invalidPan: "చెల్లని పాన్ ఫార్మాట్",
    invalidMobile: "చెల్లని మొబైల్ నంబర్",
  },
  [Language.KN]: {
    welcome: "ಸ್ವಾಗತ",
    loginSubtitle: "ನಿಮ್ಮ ಹಣಕಾಸು ಸಾಧನಗಳನ್ನು ಪ್ರವೇಶಿಸಲು ಸೈನ್ ಇನ್ ಮಾಡಿ",
    login: "ಲಾಗಿನ್",
    signup: "ಸೈನ್ ಅಪ್",
    email: "ಇಮೇಲ್ ವಿಳಾಸ",
    password: "ಪಾಸ್‌ವರ್ಡ್",
    name: "ಪೂರ್ಣ ಹೆಸರು",
    logout: "ಲಾಗ್ ಔಟ್",
    totalExpenses: "ಒಟ್ಟು ವೆಚ್ಚಗಳು",
    monthlyBudget: "ಮಾಸಿಕ ಬಜೆಟ್",
    remaining: "ಉಳಿದಿದೆ",
    recentActivity: "ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ",
    calculate: "ಲೆಕ್ಕ ಹಾಕಿ",
    amount: "ಮೊತ್ತ",
    interestRate: "ಬಡ್ಡಿ ದರ (%)",
    tenure: "ಅವಧಿ (ವರ್ಷಗಳು)",
    monthlyEMI: "ಮಾಸಿಕ EMI",
    totalInterest: "ಒಟ್ಟು ಬಡ್ಡಿ",
    totalPayment: "ಒಟ್ಟು ಪಾವತಿ",
    analyze: "ವಿಶ್ಲೇಷಿಸಿ",
    fraudPlaceholder: "ಅನುಮಾನಾಸ್ಪದ SMS ಅಥವಾ ಇಮೇಲ್ ಅನ್ನು ಇಲ್ಲಿ ಪೇಸ್ಟ್ ಮಾಡಿ...",
    fraudTitle: "ವಂಚನೆ ಪತ್ತೆಗಾರ",
    safe: "ಸುರಕ್ಷಿತ",
    suspicious: "ಅನುಮಾನಾಸ್ಪದ",
    dangerous: "ಅಪಾಯಕಾರಿ",
    expenseTitle: "ವೆಚ್ಚ ಟ್ರ್ಯಾಕರ್",
    addExpense: "ವೆಚ್ಚ ಸೇರಿಸಿ",
    category: "ವರ್ಗ",
    date: "ದಿನಾಂಕ",
    loanTitle: "AI ಸಾಲ ಅರ್ಹತೆ",
    income: "ಮಾಸಿಕ ಆದಾಯ",
    creditScore: "ಕ್ರೆಡಿಟ್ ಸ್ಕೋರ್",
    existingEmi: "ಅಸ್ತಿತ್ವದಲ್ಲಿರುವ EMI",
    predict: "ಅರ್ಹತೆಯನ್ನು ಊಹಿಸಿ",
    chatPlaceholder: "ಹಣಕಾಸಿನ ಬಗ್ಗೆ ಏನನ್ನಾದರೂ ಕೇಳಿ...",
    analyzing: "ವಿಶ್ಲೇಿಸಲಾಗುತ್ತಿದೆ...",
    processing: "ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುತ್ತಿದೆ...",
    heroTitle: "ನಿಮ್ಮ ಬುದ್ಧಿವಂತ ಹಣಕಾಸು ಸಂಗಾತಿ",
    heroSubtitle: "AI ಮತ್ತು ಸ್ಮಾರ್ಟ್ ಪರಿಕರಗಳೊಂದಿಗೆ ನಿಮ್ಮ ಹಣವನ್ನು ನಿರ್ವಹಿಸಿ.",
    getStarted: "ಉಚಿತವಾಗಿ ಪ್ರಾರಂಭಿಸಿ",
    noAccount: "ಖಾತೆ ಇಲ್ಲವೇ? ಸೈನ್ ಅಪ್",
    hasAccount: "ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ? ಲಾಗಿನ್",
    loginError: "ತಪ್ಪು ಇಮೇಲ್ ಅಥವಾ ಪಾಸ್‌ವರ್ಡ್.",
    signupError: "ಬಳಕೆದಾರರು ಈಗಾಗಲೇ ಇದ್ದಾರೆ. ಲಾಗಿನ್ ಮಾಡಿ.",
    userNotFound: "ಬಳಕೆದಾರರು ಕಂಡುಬಂದಿಲ್ಲ. ದಯವಿಟ್ಟು ಸೈನ್ ಅಪ್ ಮಾಡಿ.",
    features: "ವೈಶಿಷ್ಟ್ಯಗಳು",
    transferTitle: "ಹಣ ವರ್ಗಾವಣೆ",
    recipient: "ಸ್ವೀಕರಿಸುವವರ ಹೆಸರು",
    accountNo: "ಖಾತೆ ಸಂಖ್ಯೆ / UPI ID",
    sendMoney: "ಹಣ ಕಳುಹಿಸಿ",
    successMsg: "ವಹಿವಾಟು ಯಶಸ್ವಿಯಾಗಿದೆ!",
    history: "ವಹಿವಾಟು ಇತಿಹಾಸ",
    walletBalance: "ವ್ಯಾಲೆಟ್ ಬ್ಯಾಲೆನ್ಸ್",
    insuranceTitle: "ವಿಮಾ ಸಲಹೆಗಾರ",
    lifeInsurance: "ಜೀವ ವಿಮೆ",
    healthInsurance: "ಆರೋಗ್ಯ ವಿಮೆ",
    vehicleInsurance: "ವಾಹನ ವಿಮೆ",
    age: "ವಯಸ್ಸು",
    coverage: "ಕವರೇಜ್ ಮೊತ್ತ",
    premium: "ಅಂದಾಜು ಪ್ರೀಮಿಯಂ",
    getQuote: "ಕೋಟ್ ಪಡೆಯಿರಿ",
    recommended: "ಶಿಫಾರಸು ಮಾಡಿದ ಯೋಜನೆಗಳು",
    googleLogin: "Google ನೊಂದಿಗೆ ಮುಂದುವರಿಯಿರಿ",
    signupSuccess: "ಖಾತೆ ರಚಿಸಲಾಗಿದೆ! ದಯವಿಟ್ಟು ಲಾಗಿನ್ ಮಾಡಿ.",
    valName: "ಹೆಸರು ಅಗತ್ಯವಿದೆ",
    valEmail: "ದಯವಿಟ್ಟು ಮಾನ್ಯವಾದ ಇಮೇಲ್ ವಿಳಾಸವನ್ನು ನಮೂದಿಸಿ",
    valPass: "ಪಾಸ್‌ವರ್ಡ್ ಕನಿಷ್ಠ 6 ಅಕ್ಷರಗಳಿರಬೇಕು",
    paymentMethod: "ಪಾವತಿ ವಿಧಾನ",
    payWith: "ಮೂಲಕ ಪಾವತಿಸಿ",
    processingPayment: "ಪಾವತಿಯನ್ನು ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುತ್ತಿದೆ...",
    enterPin: "UPI ಪಿನ್ ನಮೂದಿಸಿ",
    pinPlaceholder: "4-ಅಂಕಿಯ ಪಿನ್ ನಮೂದಿಸಿ",
    invalidPin: "ತಪ್ಪು ಪಿನ್",
    securePayment: "ಸುರಕ್ಷಿತ ಪಾವತಿ",
    paying: "ಪಾವತಿಸಲಾಗುತ್ತಿದೆ",
    currentScore: "ಪ್ರಸ್ತುತ ಸ್ಕೋರ್",
    scoreHistory: "ಸ್ಕೋರ್ ಇತಿಹಾಸ",
    factors: "ಪ್ರಮುಖ ಅಂಶಗಳು",
    checkScore: "ಸ್ಕೋರ್ ರಿಫ್ರೆಶ್ ಮಾಡಿ",
    paymentHistory: "ಪಾವತಿ ಇತಿಹಾಸ",
    utilization: "ಕ್ರೆಡಿಟ್ ಬಳಕೆ",
    impact: "ಪರಿಣಾಮ",
    excellent: "ಅತ್ಯುತ್ತಮ",
    good: "ಉತ್ತಮ",
    fair: "ಸಾಧಾರಣ",
    poor: "ಕಳಪೆ",
    enterDetails: "ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ",
    panNumber: "ಪ್ಯಾನ್ ಸಂಖ್ಯೆ",
    dob: "ಹುಟ್ಟಿದ ದಿನಾಂಕ",
    mobileNumber: "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
    checkNow: "ಈಗ ಪರಿಶೀಲಿಸಿ",
    cardEligibility: "ಕಾರ್ಡ್ ಅರ್ಹತೆ",
    checkEligibility: "ಅರ್ಹತೆಯನ್ನು ಪರಿಶೀಲಿಸಿ",
    recommendedCards: "ಶಿಫಾರಸು ಮಾಡಿದ ಕಾರ್ಡ್‌ಗಳು",
    applyNow: "ಈಗಲೇ ಅರ್ಜಿ ಹಾಕಿ",
    annualFee: "ವಾರ್ಷಿಕ ಶುಲ್ಕ",
    joiningFee: "ಸೇರ್ಪಡೆ ಶುಲ್ಕ",
    salaried: "ವೇತನದಾತ",
    selfEmployed: "ಸ್ವಯಂ ಉದ್ಯೋಗಿ",
    student: "ವಿದ್ಯಾರ್ಥಿ",
    employmentType: "ಉದ್ಯೋಗದ ಪ್ರಕಾರ",
    invalidPan: "ಅಮಾನ್ಯವಾದ PAN ಸ್ವರೂಪ",
    invalidMobile: "ಅಮಾನ್ಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
  },
  [Language.BN]: {
    welcome: "স্বাগতম",
    loginSubtitle: "আপনার আর্থিক সরঞ্জামগুলি অ্যাক্সেস করতে সাইন ইন করুন",
    login: "লগ ইন",
    signup: "সাইন আপ",
    email: "ইমেল ঠিকানা",
    password: "পাসওয়ার্ড",
    name: "পুরো নাম",
    logout: "লগ আউট",
    totalExpenses: "মোট খরচ",
    monthlyBudget: "মাসিক বাজেট",
    remaining: "অবশিষ্ট",
    recentActivity: "সাম্প্রতিক কার্যকলাপ",
    calculate: "গণনা করুন",
    amount: "পরিমাণ",
    interestRate: "সুদের হার (%)",
    tenure: "মেয়াদ (বছর)",
    monthlyEMI: "মাসিক EMI",
    totalInterest: "মোট সুদ",
    totalPayment: "মোট পেমেন্ট",
    analyze: "বিশ্লেষণ করুন",
    fraudPlaceholder: "সন্দেহজনক এসএমএস বা ইমেল এখানে পেস্ট করুন...",
    fraudTitle: "প্রতারণা সনাক্তকারী",
    safe: "নিরাপদ",
    suspicious: "সন্দেহজনক",
    dangerous: "বিপজ্জনক",
    expenseTitle: "খরচ ট্র্যাকার",
    addExpense: "খরচ যোগ করুন",
    category: "বিভাগ",
    date: "তারিখ",
    loanTitle: "AI ঋণের যোগ্যতা",
    income: "মাসিক আয়",
    creditScore: "ক্রেডিট স্কোর",
    existingEmi: "বিদ্যমান EMI",
    predict: "যোগ্যতা পূর্বাভাস",
    chatPlaceholder: "অর্থ সম্পর্কে আমাকে যা খুশি জিজ্ঞাসা করুন...",
    analyzing: "বিশ্লেষণ করা হচ্ছে...",
    processing: "প্রক্রিয়া করা হচ্ছে...",
    heroTitle: "আপনার বুদ্ধিমান আর্থিক সঙ্গী",
    heroSubtitle: "AI এবং স্মার্ট টুলের সাহায্যে আপনার অর্থ ব্যবস্থাপনা করুন।",
    getStarted: "বিনামূল্যে শুরু করুন",
    noAccount: "অ্যাকাউন্ট নেই? সাইন আপ",
    hasAccount: "ইতিমধ্যে অ্যাকাউন্ট আছে? লগ ইন",
    loginError: "ভুল ইমেল বা পাসওয়ার্ড।",
    signupError: "ব্যবহারকারী ইতিমধ্যে বিদ্যমান। লগ ইন করুন।",
    userNotFound: "ব্যবহারকারী পাওয়া যায়নি। সাইন আপ করুন।",
    features: "বৈশিষ্ট্য",
    transferTitle: "টাকা স্থানান্তর",
    recipient: "প্রাপকের নাম",
    accountNo: "অ্যাকাউন্ট নম্বর / UPI ID",
    sendMoney: "টাকা পাঠান",
    successMsg: "লেনদেন सफल!",
    history: "লেনদেন ইতিহাস",
    walletBalance: "ওয়ালেট ব্যালেন্স",
    insuranceTitle: "বীমা উপদেষ্টা",
    lifeInsurance: "জীবন বীমা",
    healthInsurance: "স্বাস্থ্য বীমা",
    vehicleInsurance: "গাড়ি বীমা",
    age: "বয়স",
    coverage: "কভারেজ পরিমাণ",
    premium: "আনুমানিক প্রিমিয়াম",
    getQuote: "কোট পান",
    recommended: "সুপারিশকৃত পরিকল্পনা",
    googleLogin: "Google এর সাথে চালিয়ে যান",
    signupSuccess: "অ্যাকাউন্ট তৈরি হয়েছে! দয়া করে লগ ইন করুন।",
    valName: "নাম প্রয়োজন",
    valEmail: "অনুগ্রহ করে একটি বৈধ ইমেল ঠিকানা লিখুন",
    valPass: "পাসওয়ার্ড কমপক্ষে 6 অক্ষরের হতে হবে",
    paymentMethod: "পেমেন্ট পদ্ধতি",
    payWith: "দিয়ে পেমেন্ট করুন",
    processingPayment: "পেমেন্ট প্রক্রিয়া করা হচ্ছে...",
    enterPin: "UPI পিন দিন",
    pinPlaceholder: "4-সংখ্যার পিন দিন",
    invalidPin: "ভুল পিন",
    securePayment: "নিরাপদ পেমেন্ট",
    paying: "পেমেন্ট হচ্ছে",
    currentScore: "বর্তমান স্কোর",
    scoreHistory: "স্কোর ইতিহাস",
    factors: "মূল বিষয়",
    checkScore: "স্কোর রিফ্রेश করুন",
    paymentHistory: "পেমেন্ট ইতিহাস",
    utilization: "ক্রেডিট ব্যবহার",
    impact: "প্রভাব",
    excellent: "চমৎকার",
    good: "ভালো",
    fair: "মোটামুটি",
    poor: "খারাপ",
    enterDetails: "বিবরণ লিখুন",
    panNumber: "প্যান নম্বর",
    dob: "জন্ম তারিখ",
    mobileNumber: "মোবাইল নম্বর",
    checkNow: "এখনই চেক করুন",
    cardEligibility: "কার্ড যোগ্যতা",
    checkEligibility: "যোগ্যতা যাচাই করুন",
    recommendedCards: "সুপারিশকৃত কার্ড",
    applyNow: "এখনই আবেদন করুন",
    annualFee: "বার্ষিক ফি",
    joiningFee: "যোগদান ফি",
    salaried: "বেতনভোগী",
    selfEmployed: "স্বনিযুক্ত",
    student: "ছাত্র",
    employmentType: "কর্মসংস্থানের ধরন",
    invalidPan: "অবৈধ প্যান ফর্ম্যাট",
    invalidMobile: "অবৈধ মোবাইল নম্বর",
  }
};